version: "3.8"
services:
  dynatrace-oneagent:
    image: dynatrace/oneagent:latest
    restart: on-failure:5
    read_only: true
    pid: "host"
    network_mode: "host"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - KILL
      - NET_ADMIN
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETUID
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
      - SYS_RESOURCE
    security_opt:
      - apparmor:unconfined
    volumes:
      - "/:/mnt/root"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - ONEAGENT_ENABLE_VOLUME_STORAGE=true
      - ONEAGENT_INSTALLER_SCRIPT_URL=<SUA-URL>
      - ONEAGENT_INSTALLER_DOWNLOAD_TOKEN=<SEU-TOKEN>
  
  sample-dynatrace-api:
    build:
      context: ../src/Sample.Dynatrace.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always